services:
  - type: web
    name: tailortalk-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://shaikmahammadhussain835:pgBZgM9gYvXmLzw1@hussain.vo52sy7.mongodb.net/?retryWrites=true&w=majority&appName=Hussain
      - key: PORT
        value: 8000
    
  - type: web
    name: tailortalk-frontend
    env: python
    buildCommand: cd frontend && pip install -r requirements.txt
    startCommand: cd frontend && streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://tailortalk-backend.onrender.com

